version: '3.5'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.2
    hostname: zookeeper
    restart: always
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/secrets/zookeeper_jaas.conf
                  -Dzookeeper.authProvider.1=org.apache.zookeeper.server.auth.SASLAuthenticationProvider
                  -DrequireClientAuthScheme=sasl
                  -Dzookeeper.allowSaslFailedClients=false
    volumes:
      - ./secrets:/etc/kafka/secrets
      - ./logs/:/var/log/kafka/

  broker:
    image: confluentinc/cp-kafka:7.2.2
    hostname: broker
    restart: always
    ports:
      - "9092:9092"
      - "29092:29092"
    volumes:
      - ./secrets:/etc/kafka/secrets
      - ./logs/:/var/log/kafka/
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_INTER_BROKER_LISTENER_NAME: SASL_SSL
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: SASL_SSL:SASL_SSL
      KAFKA_ADVERTISED_LISTENERS: SASL_SSL://broker:9092
      KAFKA_LISTENERS: SASL_SSL://:9092
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_SSL_KEYSTORE_FILENAME: kafka.broker.keystore.jks
      KAFKA_SSL_KEYSTORE_CREDENTIALS: broker_keystore_creds
      KAFKA_SSL_KEY_CREDENTIALS: broker_sslkey_creds
      KAFKA_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/kafka.broker.truststore.jks
      KAFKA_SSL_KEYSTORE_CREDENTIALS: broker_keystore_creds
      # enables 2-way authentication
      #KAFKA_SSL_CLIENT_AUTH: "required"
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: "HTTPS"
      KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/secrets/broker_jaas.conf
      #KAFKA_SSL_PRINCIPAL_MAPPING_RULES: RULE:^CN=(.*?),OU=TEST.*$$/$$1/,DEFAULT
  clickhouse:
    image: yandex/clickhouse-server:ci_build_pr7935
    build:
      context: ci_build/.
    ports:
      - "9000:9000"
      - "9009:9009"
      - "8123:8123"
    hostname: clickhouse
    volumes:
      - ./configs/extra_config.xml:/etc/clickhouse-server/config.d/extra_config.xml
      - ./secrets:/etc/clickhouse-server/ssl/
      - ./logs/:/var/log/clickhouse-server/
    privileged: true # the easiest option to make perf and other debug tools work in the container
    security_opt:
      - label:disable

  kafkacat:
    image: confluentinc/cp-kafkacat
    entrypoint: tail -f /dev/null